텐서플로 2와 머신러닝으로 시작하는 자연어 처리 

## 02_1 scikit-learn
- Iris classify

In [1]:
import sklearn
sklearn.__version__

'0.24.2'

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris_dataset = load_iris()
print("iris_dataset key: {}".format(iris_dataset.keys()))

iris_dataset key: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [4]:
print(iris_dataset['data'])
print("shape of data: {}".format(iris_dataset['data'].shape))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
print(iris_dataset['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print(iris_dataset['target'])
print("shape of data: {}".format(iris_dataset['target'].shape))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
shape of data: (150,)


In [7]:
print(iris_dataset['target_names'])
print("shape of data: {}".format(iris_dataset['target_names'].shape))

['setosa' 'versicolor' 'virginica']
shape of data: (3,)


In [8]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

사이킷런을 이용한 데이터 분리
- 학습 데이터와 평가 데이터로 나누가
    - train_test_split 를 불러와 사용,
    - train_test_split 은 sklearn.model_selection 안에 있다

1. 나누고 싶은 데이터 입력 
    - 여기서는 데이터과 라벨값을 넣음
2. 평가 데이터의 크기 결정
    - 0~1 사이의 값 (퍼센트)
3. random_state=n 값을 설정
    - random-state 는 수행시마다 동일한 값을 얻기 위해 적용
    - 

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'], 
                                                                   iris_dataset['target'],
                                                                   test_size = 0.25, random_state=42)

In [14]:
print("shape of train_input: {}".format(train_input.shape))
print("shape of test_input: {}".format(test_input.shape))
print("shape of train_label: {}".format(train_label.shape))
print("shape of test_label: {}".format(test_label.shape))

shape of train_input: (112, 4)
shape of test_input: (38, 4)
shape of train_label: (112,)
shape of test_label: (38,)


사이킷런을 이용한 지도 학습
- k-최근접 이웃 분류기 사용 

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)
# k-최근접 이웃 분류기는 n_neighbors에 인자 값을 받는다. 이 숫자가 k값을 의미한다

In [18]:
# 모델 학습: fit 함수를 사용해 분류기 모델에 학습 데이터와 라벨 값을 적용
knn.fit(train_input, train_label)

KNeighborsClassifier(n_neighbors=1)

In [19]:
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=1, n_neighbors=1, p=2,
                    weights='uniform')

KNeighborsClassifier(n_jobs=1, n_neighbors=1)

학습시킨 모델을 사용해 새로운 데이터의 라벨 예측
- 4개의 새로운 피처값을 임의로 설정해서 넘파이 배열로 생성

In [22]:
import numpy as np
new_input = np.array([[6.1, 2.8, 4.7, 1.2]])

# 넘파이 배열이기 떄문에 리스트 안에 리스트가 포함된 식으로 만들어야 한다. 하나의 리스트로 만들면 오류가 난다
# 꽃받침 길이: 6.1
# 꽃받침 너비: 2.8
# 꽃잎의 길이: 4.7
# 꽃잎의 너비: 1.2

In [23]:
# 새로운 값을 대상으로 앞에서 만든 분류기 모델의 predict 함수를 사용해 결과를 예측
knn.predict(new_input)

array([1])

NameError: name 'array' is not defined