In [1]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [3]:
type(x)

numpy.ndarray

In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [5]:
x +y

array([3., 6., 9.])

In [6]:
x - y

array([-1., -2., -3.])

In [7]:
y - x

array([1., 2., 3.])

In [8]:
x -1 

array([0., 1., 2.])

In [9]:
y -2

array([0., 2., 4.])

In [10]:
x * y

array([ 2.,  8., 18.])

In [11]:
x / y

array([0.5, 0.5, 0.5])

In [13]:
A = np.array([[1,2], [3,4]])

In [14]:
print(A)

[[1 2]
 [3 4]]


In [15]:
A.shape

(2, 2)

In [18]:
type(A)

numpy.ndarray

In [19]:
A.dtype

dtype('int64')

In [22]:
B = np.array([[3,0],[0,6]])

In [23]:
B.shape

(2, 2)

In [24]:
C = np.array([[1,3],[3,3],[5,6]])

In [26]:
C.shape

(3, 2)

In [29]:
D = np.array([[3,4,5],[5,4,4],[5,1,6],[3,2,4]])
D.shape

(4, 3)

In [30]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [31]:
A *B

array([[ 3,  0],
       [ 0, 24]])

In [34]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20]])

In [35]:
A * B

array([[10, 40],
       [30, 80]])

In [37]:
X = np.array([[51,55], [14,19], [0,4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [38]:
X = X.flatten()

In [39]:
print(X)

[51 55 14 19  0  4]


In [40]:
X[np.array([0,2,4])]

array([51, 14,  0])

In [41]:
X > 15

array([ True,  True, False,  True, False, False])

In [42]:
X[X>15]

array([51, 55, 19])

In [43]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x = np.arange