In [25]:
import tensorflow as tf
from tensorflow.keras import preprocessing
from tensorflow.keras import layers
import numpy as np

In [26]:
samples = ['너 오늘 이뻐 보인다',
          '나는 오늘 기분이 더러워',
          '끝내주는데, 좋은 일이 있나봐',
          '나 좋은 일이 생겼어',
          '아 오늘 진짜 짜증나',
          '환상적인데, 정말 좋은거 같아']
targets = [[1], [0], [1],[1],[0],[1]]

In [27]:
tokenizer = preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(samples)

In [28]:
print(tokenizer.word_index)

{'오늘': 1, '좋은': 2, '일이': 3, '너': 4, '이뻐': 5, '보인다': 6, '나는': 7, '기분이': 8, '더러워': 9, '끝내주는데': 10, '있나봐': 11, '나': 12, '생겼어': 13, '아': 14, '진짜': 15, '짜증나': 16, '환상적인데': 17, '정말': 18, '좋은거': 19, '같아': 20}


In [29]:
sequences = tokenizer.texts_to_sequences(samples)
print(sequences)

[[4, 1, 5, 6], [7, 1, 8, 9], [10, 2, 3, 11], [12, 2, 3, 13], [14, 1, 15, 16], [17, 18, 19, 20]]


In [30]:
input_sequences = np.array(sequences)

In [31]:
word_index = tokenizer.word_index

In [32]:
print(input_sequences)

[[ 4  1  5  6]
 [ 7  1  8  9]
 [10  2  3 11]
 [12  2  3 13]
 [14  1 15 16]
 [17 18 19 20]]


In [33]:
print(labels)

NameError: name 'labels' is not defined

In [34]:
batch_size=2
num_epochs=100

In [35]:
vocap_size = len(word_index)+1
emb_size =128
hidden_dimension = 256
output_dimensipn =1 

In [37]:
model = tf.keras.Sequential()
model.add(layers.Embedding(vocab_size, emb_size, input_length=4))
model.add(layers.Lambda(lambda x: tf.reduce_mean(x, axis=1)))
# 차원을 줄여주는 역할. 
model.add(layers.Dense(hidden_dimension, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.Adam(0.001), metrics=['accuracu'])


NameError: name 'vocab_size' is not defined

In [38]:
model.fit(input_sequences, labels, epoch=num_epochs, batch_size=batch_size)

NameError: name 'labels' is not defined